### ISSUE TITLE
LEGO color quantization prototype

### ISSUE THREAD

**Issue by jamiejzhang17** [brick-a-pic/brick-a-pic#10]

**Comment by jamiejzhang17** [comment]
LEGO color approximation is done for the primary colors. Next step is to import a LEGO color cvs to support all lego colors. Another goal is to let users select which colors they want to use as they might not have certain colors.

**Comment by centipeda** [comment]
Partially implemented by #23.

**Comment by centipeda** [comment]
Since the pull for this prototype has been merged, let's turn those things into separate issues
