### ISSUE TITLE
Add gridlines / row & column numbers to SVG preview

### ISSUE THREAD

**Issue by centipeda** [brick-a-pic/brick-a-pic#19]
Add a set of gridlines to the mosaic as well as some kind of grid numbering, so that it's easier for a user to reference certain blocks.

**Comment by stephen-hannon** [comment]
The gridlines could be as simple as adding a stroke to each "Lego" square

**Comment by leonzzn** [comment]
Next step is to add options for user to select whether to display the grid or not.
