### ISSUE TITLE
Include all LEGO colors in quantization process

### ISSUE THREAD

**Issue by centipeda** [brick-a-pic/brick-a-pic#25]
Not all 39 LEGO colors are included in the quantization process, but it would probably improve color fidelity, and give users more power to pick from the bricks that they have.

One suggestion was to load the list of color values from a CSV or somesuch.

**Comment by centipeda** [comment]
There are a bunch of different sources for the RGB values, apparently...
https://brickset.com/colours/chart  
https://rebrickable.com/colors/

This one might be the easiest to extract the colors from, though:  
http://www.peeron.com/cgi-bin/invcgis/colorguide.cgi

**Comment by centipeda** [comment]
Did some basic processing from that last link:
[colors.txt](https://github.com/brick-a-pic/brick-a-pic/files/4256067/colors.txt)  
[colors.csv.txt](https://github.com/brick-a-pic/brick-a-pic/files/4256078/colors.csv.txt)

**Comment by jamiejzhang17** [comment]
Done
