### ISSUE TITLE
Handle non-square images

### ISSUE THREAD

**Issue by stephen-hannon** [brick-a-pic/brick-a-pic#29]
Currently all images being uploaded are squashed into being square. They should scale to be the correct aspect ratio.

**Comment by stephen-hannon** [comment]
@SwellsHub This might be related to what you're working on in #28

**Comment by SwellsHub** [comment]
@stephen-hannon yeah I'm working on this

**Comment by centipeda** [comment]
Partially implemented now. I can hook into the image data now.
