### ISSUE TITLE
Sketch out UI/Design of web site, map out user experience

### ISSUE THREAD

**Issue by SwellsHub** [brick-a-pic/brick-a-pic#3]
Create mock up of site and map out what the experience of using the site will be.

**Comment by SwellsHub** [comment]
![image](https://user-images.githubusercontent.com/41546717/74108159-60f95100-4b45-11ea-99a6-a5f6e28a3e78.png)

**Comment by centipeda** [comment]
@SwellsHub could you drop the full UI mockups here, too?

**Comment by SwellsHub** [comment]
![image](https://user-images.githubusercontent.com/41546717/74264268-62a25080-4cce-11ea-9af9-dd5341b7a049.png)
