### ISSUE TITLE
Change dimension values to sliders

### ISSUE THREAD

**Issue by centipeda** [brick-a-pic/brick-a-pic#38]
I was thinking it might make more sense visually to have the 'width' and 'height' parameters show up as sliders, instead of text boxes. 

Or, maybe even both, with the slider & text box changing each other. This might not be very difficult to implement, given v-model, [v-slider](https://vuetifyjs.com/en/components/sliders), and [v-text-field](https://vuetifyjs.com/en/components/text-fields). 

Input would be appreciated.

**Comment by stephen-hannon** [comment]
Agreed that doing both would probably be most user-friendly
