### ISSUE TITLE
Investigate related projects to ours

### ISSUE THREAD

**Issue by centipeda** [brick-a-pic/brick-a-pic#4]

**Comment by leonzzn** [comment]
- Related Work: Identify any relevant related work (ie. existing projects, products, software, etc.).
    - Consider what you can take or learn from this related work.
    - Describe how your project is different for this related work.

**Comment by leonzzn** [comment]
**Legoizer**

**Input**: an image

**Output**: lego-like images

**Advantages**: 
•  detailed description about **size of the lego image** ("your lego wall is 5’3’’ wide and 2’9’’ tall")
•  **number** of each **size** and **color** the bricks (314 1*2 earth blue, 268 2*2 black, 7 6*2 medium stone grey)
•  **instructions** of the bricks to use in lines
•  bricks in **Lego palette**

**Restrictions**:
•  The suggested size of the lego image could be **irrational** ("5'3'' and 2'9''")
•  **No customizations** 

https://sailorhg.github.io/legoizer/

**Comment by leonzzn** [comment]
**Bricks camera**

**Input**: real-time camera / an image

**Output**: lego-like image or gif

**Advantages**:
•  could process both **images** and **video clips**
•  takes **lens** as input option
•  **adjustable** brick size / pixel resolution

**Restrictions**:
•  the generated color could be **weird** 

https://horizon.camera/bricks/

**Comment by leonzzn** [comment]
**Legofy** 

**Input**: an image

**Output**: lego-like images

**Advantages**:
•  adjustable brick size
•  adjustable blend mode
•  allow re-rendering

https://github.com/Wildhoney/Legofy

Notes: there are a few of other github open source projects that are doing the similar task, Legofy is representative

**Comment by leonzzn** [comment]
**Brick-a-pic**

**Input**: an image

**Output**: lego brick mosaics

**Advantages**:
•  adjustable size and colors
•. allow selecting **part of the image**

**Restrictions**:
•  Bad performance if the input image has a **high resolution**

https://www.brickapic.com/

https://www.kickstarter.com/projects/77057469/brick-a-pic-turn-an-image-into-lego-bricks

**Comment by leonzzn** [comment]
RgbQuant.js

This is a relevant **image quantization library** that reduces an image with thousands of colors to one with fewer.

This library could be a potential external library that help to customize the number of colors.  

https://github.com/leeoniya/RgbQuant.js/tree/master

**Comment by leonzzn** [comment]
Takeaway: 
Just as our conception of the image rasterization, all of the other relevant existing projects take either an image as input by letting the user either upload a picture or take one on their own. It would be better if our own implementation could support:

1. Customization of resolution / number of bricks to use
2. Different palettes
3.  Instructions of the bricks

**Comment by centipeda** [comment]
**POPMosaic**

* Kickstarter project
* Only allows for viewing image demo

Advantages:
* Images are quantized relatively nicely to LEGO colors

Disadvantages: 
* LEGO instructions are paid backer rewards

Notes:
* The outlined 'instruction sheet' might be useful for us to implement somehow:
![](https://ksr-ugc.imgix.net/assets/027/579/304/79a23682614c3ebf92818f3b562279d1_original.PNG?ixlib=rb-2.1.0&w=680&fit=max&v=1577189533&auto=format&gif-q=50&lossless=true&s=b51a712e963ecdb6a3897bd900a1cafe)

https://www.kickstarter.com/projects/popmosaic/popmoisaicfun-your-pictures-in-mosaics-made-of-lego
