### ISSUE TITLE
Update sample images

### ISSUE THREAD

**Issue by centipeda** [brick-a-pic/brick-a-pic#47]
Our sample images don't quite convey what our app can do now. Any suggestions for the new sample images? Maybe those that convert nicely to LEGO colors, or have varying size and shape.

They could even trigger a set of pre-configured settings like size and color palette... although that might be left for later.

**Comment by AndroidKitKat** [comment]
Use this one 

![Use this one](https://user-images.githubusercontent.com/39808659/75996970-a7d03180-5ecc-11ea-99bc-ce2a3884c1f1.jpg)

**Comment by centipeda** [comment]
![image](https://user-images.githubusercontent.com/16915320/75997276-1ca36b80-5ecd-11ea-8a8b-e362e8211380.png)

**Comment by AndroidKitKat** [comment]
I'll take your entire stock

**Comment by centipeda** [comment]
![free](https://user-images.githubusercontent.com/16915320/75997829-eb776b00-5ecd-11ea-9b0f-7a4586e53bf3.jpg)

**Comment by centipeda** [comment]
![DSC07048](https://user-images.githubusercontent.com/16915320/76001953-e4ebf200-5ed3-11ea-8368-fd2ed6b92cd9.JPG)
![image](https://user-images.githubusercontent.com/16915320/76001949-e2899800-5ed3-11ea-8d3e-741d61acba7b.png)
