### ISSUE TITLE
Investigate containerization/distribution options

### ISSUE THREAD

**Issue by centipeda** [brick-a-pic/brick-a-pic#5]

**Comment by jamiejzhang17** [comment]
2 most popular containerization options are **Docker** and **Kubernetes**.
Both of them are open-source.

Docker: https://docs.docker.com/engine/docker-overview/

Docker is currently the most popular containerization platform. It can package all the dependencies of an application in a "container" and it can run on any linux server. Some features of Docker are:

- Develop apps and supporting components using containers
- Containers = unit for distribution and testing
- Deploy app as a container service

To containerize a project, we can write a Dockerfile which describes how to construct a filesystem for a given container. The Dockerfile builds up an image which can be used to run the application locally as well as for deployment on servers.


Kubernetes: https://kubernetes.io/

Kubernetes functions similarly to Docker. It utilizes containers and it enables easier scalability and deployment. However, Kubernetes is very complex and it could be an overkill for simple applications.
